language: java

sudo: false

services:
  - docker

jdk:
  - oraclejdk8
  - openjdk11

addons:
  apt:
    packages:
      - rpm

install: true

cache:
  directories:
    - $HOME/.m2/repository

install: true

script:
  - mvn -P ci -B install
